version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:lts

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-pnpm-{{ checksum "pnpm-lock.yaml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-pnpm-

      - run:
          name: pnpm-install
          command: corepack enable && pnpm install --frozen-lockfile

      # In your code, add this (after installing with `pnpm install --save-dev audit-ci`):
      # - run:
      #    name: run-audit-ci
      #    command: 'audit-ci --moderate'

      - save_cache:
          paths:
            - node_modules
          key: v1-pnpm-{{ checksum "pnpm-lock.yaml" }}

      - run:
          name: run-build
          command: pnpm run build

      # Have audit-ci run audit-ci to audit itself :)
      - run:
          name: run-audit-ci
          # Only have audit-ci checks on pull requests
          command: if [[ ! -z $CIRCLE_PULL_REQUEST ]]; then node ./dist/bin.js --config ./audit-ci.jsonc; fi
      - run:
          name: run-lint
          command: pnpm run lint

      - run:
          name: run-tests
          command: pnpm run test
